name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to the latest version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated to the latest version

    - name: Log in to DockerHub
      uses: docker/login-action@v3  # Updated to the latest version
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/loan-prediction:latest .

    - name: Run tests
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/loan-prediction:latest pytest tests/

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/loan-prediction:latest
